version: "2"

linters:
  enable:
    - errcheck
    - govet
    - ineffassign
    - staticcheck
    - unused
    - misspell
    - gosec
    - revive
    - wrapcheck
  settings:
    revive:
      enable-all-rules: true
      rules:
        - name: package-comments
          disabled: true
        - name: cognitive-complexity
          disabled: true
        - name: cyclomatic
          disabled: true
        - name: function-length
          disabled: true
        - name: line-length-limit
          arguments: [120, 1]
        - name: enforce-switch-style
          arguments: ["allowNoDefault"]
        - name: add-constant
          arguments:
            - max-lit-count: "10"
              allow-strs: '"","could not generate %s file, %w"'
              allow-ints: "0,1,2,10,30,64,100"
              allow-floats: "0.0,0.,1.0,1.,2.0,2."
    errcheck:
      check-type-assertions: true
      exclude-functions:
        - fmt.Fprintln
        - fmt.Fprintf

formatters:
  enable:
    - gofmt
    - gofumpt
    - goimports
    - golines
  settings:
    golines:
      max-len: 120

run:
  concurrency: 4
  timeout: 1m
  tests: false
